# Generated by Django 3.2.12 on 2022-05-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='yadisk_root_folder_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название корневой директори'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='yadisk_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Токен яндекс диска'),
        ),
    ]
