# Generated by Django 3.2.12 on 2022-04-16 18:12

import admin.homeworks.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('homeworks', '0002_homework_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('name', models.TextField(verbose_name='Название/Text')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to=admin.homeworks.utils.get_directory_path, verbose_name='Фаил')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Справочные материалы',
                'verbose_name_plural': 'Справочные материалы',
            },
        ),
    ]
