# Generated by Django 3.2.12 on 2022-04-17 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('homeworks', '0003_resourcematerials'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.teacher', verbose_name='Учитель'),
            preserve_default=False,
        ),
    ]
